name: mygoalsapp
description: list of my goals

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  double_back_to_close_app: ^1.2.0
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  flutter_slidable: ^0.5.4
  path_provider: ^1.6.7
  simple_animations: ^2.0.1
  sky_background: ^0.1.2
  sqflite: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true